apiVersion: v1
kind: Service
metadata:
  name: vproapp-service
spec:
  ports:
  - port: 80
    targetPort: vproapp-port
    protocol: TCP
    nodePort: 30998
  selector:
    app: vproapp
  type: NodePort

#apiVersion: v1
#kind: Service
#metadata:
  #name: vproapp-service
#spec:
  #ports:
  #- port: 80
    #targetPort: vproapp-port
    #protocol: TCP
  #selector:
    #app: vproapp
  #type: LoadBalancer